---

- name: include host specific variables
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: install sysstat
  ansible.builtin.package:
    name: sysstat
    state: present

- name: template sysstat config
  ansible.builtin.template:
    src: sysstat.j2
    dest: "{{ sysstat_config_path }}"
    owner: root
    group: root
    mode: 0600

- name: enable and start sysstat service
  ansible.builtin.service:
    name: sysstat
    enabled: true
    state: started
