---

- name: include host specific variables
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: enable sadc collection using debconf
  ansible.builtin.debconf:
    name: sysstat
    question: sysstat/enable
    vtype: boolean
    value: "true"

- name: install package
  ansible.builtin.package:
    name: sysstat
    state: present

- name: template config
  ansible.builtin.template:
    src: sysstat.j2
    dest: "{{ sysstat_config_path }}"
    owner: root
    group: root
    mode: 0600

- name: ensure sadc collection is enabled
  ansible.builtin.lineinfile:
    path: /etc/default/sysstat
    regexp: "^ENABLED="
    line: "ENABLED=\"true\""

- name: enable and start service
  ansible.builtin.service:
    name: sysstat
    enabled: true
    state: started
